sudo: required
language: python
matrix:
    include:
        -   env: TOXENV=py27
        -   env: TOXENV=py36
            python: 3.6
install:
    - sudo apt-get install -y --no-install-recommends zsh
    - pip install coveralls tox
script: tox
after_success: coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
